# -*- coding: utf-8 -*-
"""mamba_paper_numbers_march19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1haep5dtQrk-2cPF6arj05HmdqDyDW1-e
"""

import requests
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta





# Step 1: Define ArXiv API query (last 3 years, searching for "Mamba")
base_url = "http://export.arxiv.org/api/query?search_query=all:mamba&start=0&max_results=1000"

response = requests.get(base_url)
if response.status_code != 200:
    raise Exception("Failed to fetch data from ArXiv API")

# Step 2: Extract publication dates using XML parsing
import xml.etree.ElementTree as ET
root = ET.fromstring(response.text)
namespaces = {"arxiv": "http://www.w3.org/2005/Atom"}

dates = []
for entry in root.findall("arxiv:entry", namespaces):
    published = entry.find("arxiv:published", namespaces).text
    date = datetime.strptime(published, "%Y-%m-%dT%H:%M:%SZ")
    if date >= datetime.now() - timedelta(days=3*365):  # Last 3 years
        dates.append(date)

# Step 3: Aggregate by 3-month intervals
df = pd.DataFrame(dates, columns=['publication_date'])
df['quarter'] = df['publication_date'].dt.to_period('Q')  # Group by Quarter (3-month period)
quarterly_counts = df.groupby('quarter').size().reset_index(name='counts')

# Step 4: Plot the data
fig, ax = plt.subplots(figsize=(7, 5))

# Bar plot (Cornflower Blue)
ax.bar(quarterly_counts['quarter'].astype(str), quarterly_counts['counts'], color='cornflowerblue', label='Number of Papers')

# Line plot (Dark Gray)
ax.plot(quarterly_counts['quarter'].astype(str), quarterly_counts['counts'], color='darkgray', marker='o', linestyle='-', label='Trend')

# Formatting
ax.set_xlabel('Quarter', fontsize = 18)
ax.set_ylabel('Number of Papers', fontsize = 18)
ax.set_title('Number of arXiv Papers Mentioning "Mamba" per Quarter (Last 3 Years)', fontsize = 11)
ax.legend(fontsize = 18)
plt.xticks(rotation=90)
plt.tight_layout()

# Save the figure
plt.savefig("mamba_papers_per_quarter_march19.png", dpi=300)

# Show the plot
plt.show()

